Add OUTDRV control
HendrikVE/Arduino-PCA9633 pull request #3
Opened 2021-04-28 08:57 UTC by jamesfowkes

This is an addition to allow use of totem-pole outputs.

Hopefully it is easy enough to understand.

2021-06-22 15:11 UTC, jamesfowkes commented
@HendrikVE Can you look over this? It would be really helpful for me (and hopefully others).

2021-06-25 11:55 UTC, HendrikVE requested changes
I'm really sorry for the delay, I didn't get a notification that you opened a PR :/ Tbh I don't know how I could test this and I am limited to prebuilt hardware so I guess I will simply trust you that you tested this on your hardware :) Nevertheless I found a bug when comparing it to the specification.

2021-06-25 11:55 UTC, HendrikVE commented on src/PCA9633.cpp
> +    newReg = prevReg & ~(0b11 << BIT_OUTDRV);
Clearing two bits would also have an effect on `OCH` in the `MODE2` register. Only the outdrv bit should be changed.

2021-06-25 11:55 UTC, HendrikVE commented on src/PCA9633.h
> +// LED driver output type, OUTDRV (page 11, MODE2 register table)
I think that should be page 12.

2021-06-25 11:55 UTC, HendrikVE commented on src/PCA9633.h
> +#define OUTDRV_OPEN_DRAIN 0
Please add:
/**
 \* The 4 LED outputs are configured with an open-drain structure
 */

2021-06-25 11:55 UTC, HendrikVE commented on src/PCA9633.h
> +#define OUTDRV_TOTEM_POLE 1
Please add:
/**
 \* The 4 LED outputs are configured with a totem pole structure
 */

2021-07-26 21:18 UTC, jamesfowkes commented
Requested changes made, apologies for the delay in getting to this.

2021-07-27 10:27 UTC, HendrikVE commented
Thanks, please remove the blank line above `#define OUTDRV_TOTEM_POLE 1` and squash afterwards. After that I gonna merge it and release a new version :)

2021-07-29 21:41 UTC, merged

2021-07-30 11:05 UTC, HendrikVE commented
Thank you for your contribution and your patience ;) A new release is on the way!